config/routes.rb
Rails.application.routes.draw do
  resources :avions
  devise_for :users
  get 'admin/indexadmin'
  get 'home/indexhome'
root :to =>'home#indexhome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avion.rb
class Avion < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :authenticate_user!
  def indexadmin
    data_array_1 = [1, 4, 3, 5, 9]
    data_array_2 = [4, 2, 10, 4, 7]
    @barv = Gchart.bar(

                :size => '300x300',
                :bar_colors => ['000000', '0088FF'],
                :title => "grafica de Barra- Tickets de viaje mas comprados",
                :bg => 'EFEFEF',
                :legend => ['España ', 'USA'],
                :data => [[1, 4, 3, 5, 9], data_array_2],
                :stacked => false,
                :legend_position => 'bottom',
                :axis_with_labels => [['x'], ['y']],
                :max_value => 15,
                :min_value => 0,
                :axis_labels => [["Ene|Fbr|Mrz|ablr|E"]],
                )






  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/avions_controller.rb
class AvionsController < ApplicationController
  before_action :set_avion, only: [:show, :edit, :update, :destroy]


  # GET /avions
  # GET /avions.json
  def index
    @avions = Avion.all
  end

  # GET /avions/1
  # GET /avions/1.json
  def show
  end

  # GET /avions/new
  def new
    @avion = Avion.new
  end

  # GET /avions/1/edit
  def edit
  end

  # POST /avions
  # POST /avions.json
  def create
    @avion = Avion.new(avion_params)

    respond_to do |format|
      if @avion.save
        format.html { redirect_to @avion, notice: 'Avion was successfully created.' }
        format.json { render :show, status: :created, location: @avion }
      else
        format.html { render :new }
        format.json { render json: @avion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avions/1
  # PATCH/PUT /avions/1.json
  def update
    respond_to do |format|
      if @avion.update(avion_params)
        format.html { redirect_to @avion, notice: 'Avion was successfully updated.' }
        format.json { render :show, status: :ok, location: @avion }
      else
        format.html { render :edit }
        format.json { render json: @avion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avions/1
  # DELETE /avions/1.json
  def destroy
    @avion.destroy
    respond_to do |format|
      format.html { redirect_to avions_url, notice: 'Avion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avion
      @avion = Avion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avion_params
      params.require(:avion).permit(:matricula, :npiloto, :apiloto, :destino, :origen, :hsalidao, :fsalidao, :hllegadad, :fllegadad)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def indexhome
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avions_helper.rb
module AvionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/_admin-barra.html.erb
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-invert navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">Vista del Administrador</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/admin/indexadmin">INICIO</a></li>
        <li><a href="/avions/new">BUZÓN</a></li>
        <li><a href="#tour">ESPACIO</a></li>
        <li><a href="#contact">ESPACIO</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="/avions">AVIONES<span class="caret"></span></a>
<ul class="dropdown-menu">

            <li><a href="/avions">Mostrar</a></li>
            <li><a href="/avions/new">Nuevo</a></li>

          </ul>
        </li>
        <li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/_carrusel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
    <img style="height: 400px;width: 1360px;"<%= image_tag "1.jpg"%>
        <div class="carousel-caption">
          <h3>New York</h3>
          <p>The atmosphere in New York is lorem ipsum.</p>
        </div>
      </div>

      <div class="item">
      <img style="height: 400px;width: 1360px;"<%= image_tag "2.jpg"%>
        <div class="carousel-caption">
          <h3>Chicago</h3>
          <p>Thank you, Chicago - A night we won't forget.</p>
        </div>
      </div>

      <div class="item">
        <img style="height: 400px;width: 1360px;"<%= image_tag "3.jpg"%>
        <div class="carousel-caption">
          <h3>LA</h3>
          <p>Even though the traffic was a mess, we had the best time playing at Venice Beach!</p>
        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

app/views/admin/indexadmin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Vista del administrador</title>
  </head>
  <body>

    <%= render 'admin-barra' %>
    <%= render 'carrusel' %>

    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Sesión Iniciada como : <strong><%= current_user.email %></strong>.
  <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<div class="container-fluid">
<br>
  <%= image_tag @barv%>
</div>


  </body>
</html>

app/views/avions/_admin-barra.html.erb
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-invert navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">Vista del Administrador</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/admin/indexadmin">INICIO</a></li>
        <li><a href="/avions/new">Ingreso</a></li>
        <li><a href="#tour">TOUR</a></li>
        <li><a href="#contact">CONTACT</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Aviones<span class="caret"></span></a>
<ul class="dropdown-menu">

            <li><a href="/avions">Mostrar</a></li>
            <li><a href="/avions/new">Nuevo</a></li>

          </ul>
        </li>
        <li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/avions/_barradenavegacion.html.erb

<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-invert navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">AeroApp</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">INICIO</a></li>
          <li><a href="#viajes">VIAJES</a></li>

        <li><a href="/#tour">TOUR</a></li>
        <li><a href="/#contact">CONTACTO</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">PERSONAL
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/admin/indexadmin">INICIAR SESIÓN</a></li>
          </ul>
        </li>
        <li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/avions/_busqueda.html.erb
<div id="resultadobusqueda">

</div>
<%= form_tag "avions/index", method: :get , remote: true , id: "search-form" do%>
<%=text_field_tag :keyword, nil, placeholder: "ingrese el id del avion"%>
<%=content_tag :button, type: :submit do %>
Buscar
<%end%>
<%end%>

app/views/avions/_form.html.erb
<%= form_with(model: avion, local: true) do |form| %>
  <% if avion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(avion.errors.count, "error") %> prohibited this avion from being saved:</h2>

      <ul>
      <% avion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="div1">
    <h1 Align="center">DATOS</h1>
    <div class="field">
      <%= form.label :matricula %>
      <%= form.text_field :matricula, id: :avion_matricula %>
    </div>

    <div class="field">
      <%= form.label :npiloto %>
      <%= form.text_field :npiloto, id: :avion_npiloto %>
    </div>

    <div class="field">
      <%= form.label :apiloto %>
      <%= form.text_field :apiloto, id: :avion_apiloto %>
    </div>

    <div class="field">
      <%= form.label :destino %>
      <%= form.text_field :destino, id: :avion_destino %>
    </div>

    <div class="field">
      <%= form.label :origen %>
      <%= form.text_field :origen, id: :avion_origen %>
    </div>

  </div>
<div class="div2">
  <h2 align="center">FECHA Y HORA</h2>
  <br>
  <div class="field">
    <%= form.label :hsalidao %>
    <%= form.time_select :hsalidao, id: :avion_hsalidao %>
  </div>
<br>
  <div class="field">
    <%= form.label :fsalidao %>
    <%= form.date_select :fsalidao, id: :avion_fsalidao %>
  </div>
<br>
  <div class="field">
    <%= form.label :hllegadad %>
    <%= form.time_select :hllegadad, id: :avion_hllegadad %>
  </div>

  <div class="field">
    <%= form.label :fllegadad %>
    <%= form.date_select :fllegadad, id: :avion_fllegadad %>
  </div>

</div>
<div class="div3boton">
  <div class="actions">
    <%= form.submit %>
  </div>
</div>

<% end %>

app/views/avions/edit.html.erb
<h1>Editing Avion</h1>

<%= render 'form', avion: @avion %>

<%= link_to 'Show', @avion %> |
<%= link_to 'Back', avions_path %>

app/views/avions/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <meta charset="utf-8">
    <title>Mostrar Aviones</title>
  </head>

  <%= render 'admin-barra'%>
  <body >


    <div class="table-responsive">

      <p id="notice"><%= notice %></p>
<br>
      <h1 ALIGN=center>AVIONES</h1>
      <table >
        <thead>
          <tr >
            <th>MATRICLA</th>
            <th>NOMBRES DEL PILOTO</th>
            <th>APELLIDOS DEL PILOTO</th>
            <th>DESTINO</th>
            <th>ORIGEN</th>
            <th>HORA DE SALIDA</th>
            <th>FECHA DE SALIDA</th>
            <th>HORA DE LLEGADA</th>
            <th>FECHE DE LLEGADA</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @avions.each do |avion| %>
            <tr>
              <td><%= avion.matricula %></td>
              <td><%= avion.npiloto %></td>
              <td><%= avion.apiloto %></td>
              <td><%= avion.destino %></td>
              <td><%= avion.origen %></td>
              <td><%= avion.hsalidao %></td>
              <td><%= avion.fsalidao %></td>
              <td><%= avion.hllegadad %></td>
              <td><%= avion.fllegadad %></td>
              <td><%= link_to 'MOSTRAR', avion %></td>
              <td><%= link_to 'EDITAR', edit_avion_path(avion) %></td>
              <td><%= link_to 'ELIMINAR', avion, method: :delete, data: { confirm: 'ESTÁ SEGURO?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'NUEVO AVION', new_avion_path %>

    </div>
  </body>
</html>

app/views/avions/new.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<h1>NUEVO AVION</h1>

<%= render 'form', avion: @avion %>
<div class="div3boton">
  <%= link_to 'ATRÁS', avions_path %>
</div>

app/views/avions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matricula:</strong>
  <%= @avion.matricula %>
</p>

<p>
  <strong>Npiloto:</strong>
  <%= @avion.npiloto %>
</p>

<p>
  <strong>Apiloto:</strong>
  <%= @avion.apiloto %>
</p>

<p>
  <strong>Destino:</strong>
  <%= @avion.destino %>
</p>

<p>
  <strong>Origen:</strong>
  <%= @avion.origen %>
</p>

<p>
  <strong>Hsalidao:</strong>
  <%= @avion.hsalidao %>
</p>

<p>
  <strong>Fsalidao:</strong>
  <%= @avion.fsalidao %>
</p>

<p>
  <strong>Hllegadad:</strong>
  <%= @avion.hllegadad %>
</p>

<p>
  <strong>Fllegadad:</strong>
  <%= @avion.fllegadad %>
</p>

<%= link_to 'EDITAR', edit_avion_path(@avion) %> |
<%= link_to 'ATRÁS', avions_path %>

app/views/home/_barradenavegacion.html.erb

<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-invert navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">AeroApp</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">INICIO</a></li>
          <li><a href="#viajes">VIAJES</a></li>

        <li><a href="/#tour">TOUR</a></li>
        <li><a href="/#contact">CONTACTO</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="/admin/indexadmin">PERSONAL
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/admin/indexadmin">INICIAR SESIÓN</a></li>
          </ul>
        </li>
        <li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_buscarvuelo.html.erb
<div class="contaiener-fluid">
  <!-- Container (TOUR Section) -->
  <div id="tour" class="bg-1">
    <div class="container">
      <h3 class="text-center">Próximamente Compra de boletos en linea</h3>
      <p class="text-center">Lorem ipsum we'll play you some music.<br> Remember to book your tickets!</p>
      <ul class="list-group">
        <li class="list-group-item">September <span class="label label-danger">Sold Out!</span></li>
        <li class="list-group-item">October <span class="label label-danger">Sold Out!</span></li>
        <li class="list-group-item">November <span class="badge">3</span></li>
      </ul>

      <div class="row text-center">
        <div class="col-sm-4">
          <div class="thumbnail">
            <img src="paris.jpg" alt="Paris" width="400" height="300">
            <p><strong>Paris</strong></p>
            <p>Friday 27 November 2015</p>
            <button class="btn" data-toggle="modal" data-target="#myModal">Buy Tickets</button>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="thumbnail">
            <img src="newyork.jpg" alt="New York" width="400" height="300">
            <p><strong>New York</strong></p>
            <p>Saturday 28 November 2015</p>
            <button class="btn" data-toggle="modal" data-target="#myModal">Buy Tickets</button>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="thumbnail">
            <img src="sanfran.jpg" alt="San Francisco" width="400" height="300">
            <p><strong>San Francisco</strong></p>
            <p>Sunday 29 November 2015</p>
            <button class="btn" data-toggle="modal" data-target="#myModal">Buy Tickets</button>
          </div>
        </div>
      </div>
    </div>


</div>

app/views/home/_carrusel.html.erb

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
    <img style="height: 400px;width: 1360px;"<%= image_tag "1.jpg"%>
        <div class="carousel-caption">
          <h3>New York</h3>
          <p>The atmosphere in New York is lorem ipsum.</p>
        </div>
      </div>

      <div class="item">
      <img style="height: 400px;width: 1360px;"<%= image_tag "2.jpg"%>
        <div class="carousel-caption">
          <h3>Chicago</h3>
          <p>Thank you, Chicago - A night we won't forget.</p>
        </div>
      </div>

      <div class="item">
        <img style="height: 400px;width: 1360px;"<%= image_tag "3.jpg"%>
        <div class="carousel-caption">
          <h3>LA</h3>
          <p>Even though the traffic was a mess, we had the best time playing at Venice Beach!</p>
        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

app/views/home/_carruselnewyork.html.erb
<div id="myCarousel1" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
    <img class="img-thumbnail" <%= image_tag "WaltDisneyWorld.jpg"%>
        <div class="carousel-caption">
      
        </div>
      </div>

      <div class="item">
      <img class="img-thumbnail" <%= image_tag "grancanion.jpg"%>
        <div class="carousel-caption">

        </div>
      </div>
      <div class="item">
        <img class="img-thumbnail"<%= image_tag "estatuadelalibertad.jpg"%>
        <div class="carousel-caption">


        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel1" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel1" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

app/views/home/_carruselparis.html.erb
<div id="myCarousel2" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
    <img class="img-thumbnail" <%= image_tag "torre.jpg"%>
        <div class="carousel-caption">

        </div>
      </div>

      <div class="item">
      <img class="img-thumbnail" <%= image_tag "arco.jpg"%>
        <div class="carousel-caption">

        </div>
      </div>
      <div class="item">
        <img class="img-thumbnail"<%= image_tag "paris.jpg"%>
        <div class="carousel-caption">


        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel2" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel2" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

app/views/home/_carruselrusia.html.erb
<div id="myCarousel3" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
    <img class="img-thumbnail" <%= image_tag "visitarusia.jpg"%>
        <div class="carousel-caption">

        </div>
      </div>

      <div class="item">
      <img class="img-thumbnail" <%= image_tag "moscu.jpg"%>
        <div class="carousel-caption">

        </div>
      </div>
      <div class="item">
        <img class="img-thumbnail"<%= image_tag "roja.png"%>
        <div class="carousel-caption">


        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel3" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel3" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

app/views/home/_contactos.html.erb
<!-- Container (Contact Section) -->
<div id="contact" class="container">
  <h3 class="text-center">Contáctanos</h3>
  <p class="text-center"><em>Queremos brindarle un mejor servicio</em></p>

  <div class="row">
    <div class="col-md-4">
      <p></p>
      <p><span class="glyphicon glyphicon-map-marker"></span>Masayas, Nicaragua</p>
      <p><span class="glyphicon glyphicon-phone"></span>Phone: +505-77664638</p>
      <p><span class="glyphicon glyphicon-envelope"></span>Email: ferb2013ruiz@gmail.com</p>
    </div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-sm-6 form-group">
          <input class="form-control" id="name" name="name" placeholder="Nombre" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" id="comments" name="comments" placeholder="Escribir Comentario" rows="5"></textarea>
      <br>
      <div class="row">
        <div class="col-md-12 form-group">
          <button class="btn pull-right" type="submit">Enviar</button>
        </div>
      </div>
    </div>
  </div>
  <br>

</div>

app/views/home/_footer.html.erb
<!-- Footer -->
<footer class="text-center">
  <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a><br><br>
  <p>Developers Ruby On Rails <a href="" data-toggle="tooltip" title=""></a></p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CDA1</title>
    <%= csrf_meta_tags %>
    <!-- Versión compilada y comprimida del CSS de Bootstrap -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">

    <!-- Tema opcional -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">

    <!-- Versión compilada y comprimida del JavaScript de Bootstrap -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>